### ISSUE TITLE
Implement Where They Work page

### ISSUE THREAD

**Issue by jaywon** [devleague/devleague-website#114]
We are missing design and content for the menu options under Legends->Where Do They Work?

http://localhost:3000/companies

We need to get a list of all employers in our network and those that have hired and fill this page out. Ok to hide for launch but needs to be prioritized.

**Comment by JoeKarlsson** [comment]
:construction: Yo - I got dis bros :construction:

**Comment by JoeKarlsson** [comment]
We don't have a layout for this page, so I am going to use the generic template, with a title, body and I am going to list all of the employer logos in a flex box grid. Cool beans? :+1:

**Comment by jaywon** [comment]
Perfect!

**Comment by jaywon** [comment]
Closing ticket since branch has been merged.
