### ISSUE TITLE
Have footer track options come from CMS

### ISSUE THREAD

**Issue by jaywon** [devleague/devleague-website#115]
Footer tracks are currently hard coded and not pulling from CMS and link to random things. Can we implement the way the nav menu is implemented and populate from CMS, or in any way that makes sense.

![footer](https://cloud.githubusercontent.com/assets/1680159/22814884/50648fca-eefb-11e6-867f-db786fda9421.png)

![footer-view](https://cloud.githubusercontent.com/assets/1680159/22814899/674b348c-eefb-11e6-87d3-2d465694170e.png)

**Comment by sgnl** [comment]
🚧
