### ISSUE TITLE
Finish Team page

### ISSUE THREAD

**Issue by jaywon** [devleague/devleague-website#125]
@senakamura does not have pic or bio info. Also please add Kelli, Nat, and Christie.

**Comment by JoeKarlsson** [comment]
Use the same layout that we are using on the Legends page :man_dancing:

**Comment by senakamura** [comment]
[x] - Christie
[] - Natalie
[] - Sean

**Comment by senakamura** [comment]
Sean just needs a photo, but bio content is done. Kelli, Christie and Natalie have been inputed!

**Comment by sgnl** [comment]
Re-opening because Sean needs a photo.

**Comment by senakamura** [comment]
😭

**Comment by jaywon** [comment]
@senakamura don't close your own tickets please, they should be closed when work has been marked as completed with a PR

**Comment by senakamura** [comment]
![image](https://cloud.githubusercontent.com/assets/2155125/23241165/a97eacca-f915-11e6-894f-b66bcc57113a.png)

Sean Nakamura now has an image...
