### ISSUE TITLE
Nav Bar Bugs

### ISSUE THREAD

**Issue by JoeKarlsson** [devleague/devleague-website#126]
The nav bar has some bugs:

1) The right side falls outside of the bar at certain widths:

![screenshot from 2017-02-14 11-49-44](https://cloud.githubusercontent.com/assets/4650739/22951058/e2ece096-f2ab-11e6-96f6-f38c6ee7bcc9.png)

2) On Mobile - the hamburger menu button disappears:
![screenshot from 2017-02-14 11-50-05](https://cloud.githubusercontent.com/assets/4650739/22951073/f2cd54f0-f2ab-11e6-9bb6-37a93cc8ecb5.png)

**Comment by senakamura** [comment]
c57b3707c931997321e82f9da3c86fad7b92e43d resolves this issue
