### ISSUE TITLE
Update Funding Page Styles

### ISSUE THREAD

**Issue by JoeKarlsson** [devleague/devleague-website#132]
The funding page has some style issues that need to be resolved:

* The logos need to be a consistent width and height
* The content needs to be left aligned

![devleague join the movement learn to code in hawaii 4](https://cloud.githubusercontent.com/assets/4650739/22961138/cb771ae4-f2e7-11e6-93bb-27fac2d484e8.png)

**Comment by JoeKarlsson** [comment]
Updated the funding page: 

## Desktop View

![devleague join the movement learn to code in hawaii 5](https://cloud.githubusercontent.com/assets/4650739/22999308/cc3cf18c-f37e-11e6-87c4-19a315d57781.png)



## Mobile View
![devleague join the movement learn to code in hawaii 6](https://cloud.githubusercontent.com/assets/4650739/22999325/d95659b2-f37e-11e6-8169-e67feee1e338.png)

**Comment by sgnl** [comment]
merged via b0d33b5
