### ISSUE TITLE
Footer social media icon verification

### ISSUE THREAD

**Issue by sgnl** [devleague/devleague-website#134]
Currently the icons we show for our social media section on the footer are as follows:

- G+
- Facebook
- Snapchat
- LinkedIn
- Twitter
- Instagram

![image](https://cloud.githubusercontent.com/assets/3915598/22995042/46e3b11c-f36d-11e6-8aa5-e8a19fed0386.png)

Issue: I want to make sure we are showcasing the social media accounts where we're most active on. This issue to make sure we're doing that.

Do we want to link to these other sites?

🐛  ~Snapchat - if so, needs URL~ ✅  added url
🐛 Google Plus - we active on this?

**Comment by JoeKarlsson** [comment]
All social links hooked up on the DL site - I am going to close this issue. :ok_hand:
