### ISSUE TITLE
Refactor tracks page with new portable layout

### ISSUE THREAD

**Issue by jaywon** [devleague/devleague-website#146]
![standard-format-courses](https://cloud.githubusercontent.com/assets/1680159/23140989/9d46ea94-f758-11e6-8bb3-7e1937d6934a.png)

_NOTE:_  All the "Get/Download Schedule/Curriculum" buttons for now should be a CTA link to the application for now. The download schedule e-mail capture will get implemented post-launch.

We need to refactor the current template to add the following fields to support this template:
Add fields:
- Title (Main top bold text)
- Featured Quote (Italicized text under Title, can use current Featured Quote field)
- Overview (Copy section under the Overview header, header text itself should be in layout, can reuse current Body field)
- Price (Single field for price)
- Tuition Details (Copy seen after the price, optional, tuition header text should be in layout)
- Schedule Details - (Copy seen right under the Schedule header, header text itself should be in layout)
  - This one i'm not sure about. The JS track will have two columns split as seen, every other track will have a single column that spans the width of both sections seen here. I will let you guys figure out how best to implement. Current template has (First Title, Second Title, First SubTitle, Second SubTitle), maybe some implementation of this works? Or maybe it's just 2 rich text fields as the quickest solution...idk.
- Modules - The Modules should be implemented as a collection with modules entered individually with a header and copy, associated track(grouping by track), and sort order.

Any un-used fields should be removed from the template. Please let me know if you have any questions and if any of this doesn't make sense, please call it out and we'll get fast resolution on it.

:bowing_man: :bowing_man: :bowing_man:

**Comment by sgnl** [comment]
Ill work on this

**Comment by sgnl** [comment]
Checklist:

- [ ] Title (Main top bold text)
- [ ] Featured Quote (Italicized text under Title, can use current Featured Quote field)
- [ ] Overview (Copy section under the Overview header, header text itself should be in layout, can reuse current Body field)
- [ ] Price (Single field for price)
- [ ] Tuition Details (Copy seen after the price, optional, tuition header text should be in layout)
- [ ] Schedule Details - (Copy seen right under the Schedule header, header text itself should be in layout)
- [ ] This one i'm not sure about. The JS track will have two columns split as seen, every other track will have a single column that spans the width of both sections seen here. I will let you guys figure out how best to implement. Current template has (First Title, Second Title, First SubTitle, Second SubTitle), maybe some implementation of this works? Or maybe it's just 2 rich text fields as the quickest solution...idk.
- [ ] Modules - The Modules should be implemented as a collection with modules entered individually with a header and copy, associated track(grouping by track), and sort order.

**Comment by jaywon** [comment]
@sgnl For the quote, these are coming from articles that we probably want to link to so we may need that to be a link field that has the source as well as the copy we want to include so that we can link to source.

**Comment by sgnl** [comment]
@jaywon Re: Quote

To accomplish this I think it'll make sense to have a quote section on the news item itself and link news as a "related_collection" inside of the tracks collection. I think it'll be clean.

- [x] added `quote` property as a **text-area** for items in the news collection.

**Comment by sgnl** [comment]
For Schedule: Rich-text area with an unordered list. To style, each track page has it's own css override file to use.

**Comment by sgnl** [comment]
Single Schedule:

![image](https://cloud.githubusercontent.com/assets/3915598/23240776/71aa37a8-f913-11e6-9d22-7332dd35f6ff.png)


javascript Track Schedule:

![image](https://cloud.githubusercontent.com/assets/3915598/23240785/7adcbe04-f913-11e6-805b-f8ea8c146c12.png)
