### ISSUE TITLE
Fix broken image links and add hyperlinks to sponsors

### ISSUE THREAD

**Issue by jaywon** [devleague/devleague-website#148]
When we go live we'll leave the summary on the News feed. Can you update the broken image links on the page and for the sponsor links it's good practice to provide links to other entities. Also feel free to post link to your Hackathon guide you created as a result of this too.

**Comment by JoeKarlsson** [comment]
Added links to sponsors and fixed the broken images.

**Comment by JoeKarlsson** [comment]
WIP - Adding hackathon guide to Airship

**Comment by JoeKarlsson** [comment]
I still need to add the gifs to the article, but the content has been added and formatted for the airship platform

http://devleague.airshipcms.io/news/view/i-ran-my-first-hackathon-and-so-can-you

**Comment by JoeKarlsson** [comment]
I also need to make a DL branded header image for this article. I am going to work with Sean on this.

**Comment by JoeKarlsson** [comment]
Article is finished - still need a header image.

**Comment by JoeKarlsson** [comment]
Made a header image - All done.
