### ISSUE TITLE
See if deep link functionality for application is built

### ISSUE THREAD

**Issue by jaywon** [devleague/devleague-website#15]

**Comment by jaywon** [comment]
@sgnl can we deep link into the application flow? Like if i click from the JavaScript Developer track does it give me the start dates for only that course that i want to apply for?

**Comment by sgnl** [comment]
I will work on this!

**Comment by jaywon** [comment]
@sgnl Can we close out this ticket? I believe this is complete and anything going forward would be more granular tasks?

**Comment by sgnl** [comment]
deep link was implemented via #119
