### ISSUE TITLE
Create footer pages

### ISSUE THREAD

**Issue by jaywon** [devleague/devleague-website#21]

**Comment by jaywon** [comment]
Can take existing copy/layout styles from existing site for FAQ/Terms/Privacy Policy.

**Comment by ncadiente** [comment]
Unstyled but created

**Comment by JoeKarlsson1** [comment]
Added copy from the old  DL site to the Privacy and Terms of Use pages, and I stubbed out styles, but they still need work.

**Comment by jaywon** [comment]
:+1:
