### ISSUE TITLE
Update Homepage Styles and Layout

### ISSUE THREAD

**Issue by JoeKarlsson1** [devleague/devleague-website#33]
The homepage is still pretty inconsistent and messy. I want to update the styles and the layout.

I am going to update the styles, then we can talk about what needs to be changed. I'm a little nervous since we do not have a defined style guide though.

**Comment by jaywon** [comment]
We can define a style guide. The home page definitely needs some work but I'd like to consult Kelli for some help with that so as much as possible trying to just "ignore" this for now. I definitely want to have consensus on this to move forward on as opposed to multiple people just taking cracks at it.

**Comment by JoeKarlsson1** [comment]
I think it would be a good idea to get a style guide, otherwise it's going to just be a generic and bland website. I think it would def be a good idea to get Kelli involved. 

I started mocking up a homepage and I did some work on the homepage. I am going to push up the work I did on the homepage, but I won't work on it until we have consulted Kelli on the layout.

**Comment by jaywon** [comment]
Let me know when it's on a branch I can pull down and inspect. There's a
whole site to be done, so let's focus on some of the other tasks first.

Mahalo!

*Jason Sewell*
Curriculum Developer / Co-Founder

*Dev League, LLC*
Phone: (808) 295-6205 :: Email: jason@devleague.com
