### ISSUE TITLE
Create Application page

### ISSUE THREAD

**Issue by JoeKarlsson1** [devleague/devleague-website#35]

**Comment by jaywon** [comment]
@JoeKarlsson1 what is the application page?

**Comment by JoeKarlsson1** [comment]
This is the page that students actually apply to be a part of the program. We have a ton of "Apply Now" links, but they do not lead anywhere and we do not have any application pages stubbed out yet.

**Comment by jaywon** [comment]
The application is the standalone component that @sgnl made, it will not be a part of Airship.  There will need to be a configurable URL setting for where the application link is, subdomain on prod(apply.devleague.com), probably different port locally.

I also wanted to know if the current standalone application supports deep linking into different application paths or if it's just one standard application that lists all current offerings to select from. I need to look at that but if @sgnl can clarify?

**Comment by sgnl** [comment]
I need to implement the deep-linking functionality. I will work on that and report back.

**Comment by JoeKarlsson1** [comment]
This is a duplicate issue, please see #15  - I am going to reference than close this issue.
