### ISSUE TITLE
Refactor each track page (4) into single layout

### ISSUE THREAD

**Issue by sgnl** [devleague/devleague-website#37]
Currently within the track pages there are tabs with links to other resources. The goal is to consolidate all information into one page.

example of tabs from the current javascript track page:
![image](https://cloud.githubusercontent.com/assets/3915598/20285273/0284f48c-aa65-11e6-91e1-19f418fe6e65.png)

example from the image are the links to:
- Overview
- Part-Time
- Full-Time
- Technologies

- [x] javascript track
- [x] enterprise track
- [x] database admin track
- [x] cybersecurity track

**Comment by sgnl** [comment]
It Just Works™

**Comment by JoeKarlsson1** [comment]
PR merged - closing issue.
