### ISSUE TITLE
Define application end points

### ISSUE THREAD

**Issue by jaywon** [devleague/devleague-website#4]
Ray needs endpoints for pulling upcoming course data.

**Comment by ncadiente** [comment]
course tracks: javascript-developer, enterprise-developer, database-administrator, cyber-security
http://devleague.airshipcms.io/api/aerostat_collection/upcoming-courses/category/{course_track}/aerostats

**Comment by ncadiente** [comment]
Also course tracks: part-time and full-time

**Comment by JoeKarlsson1** [comment]
@sgnl Do you have all the endpoints you need? I think it's safe to close this issue, but I want to check with you first.

**Comment by sgnl** [comment]
I have all the information I need, closing issue.
