### ISSUE TITLE
Update Styling on Team page

### ISSUE THREAD

**Issue by JoeKarlsson1** [devleague/devleague-website#42]

**Comment by senakamura** [comment]
I got this. Just a little more cleaning up: https://github.com/devleague/devleague-website/tree/style-team-page

**Comment by sgnl** [comment]
Nice work @senakamura 

I pushed some additions to the styles, I just updated the HTML to use material css and thus I could remove some CSS. I also removed some litter.

Changes the social links to a `ul>li` elements for semantic awesomeness™ and added some styles for that.
