### ISSUE TITLE
Finish Styling on News page

### ISSUE THREAD

**Issue by JoeKarlsson** [devleague/devleague-website#43]

**Comment by JoeKarlsson1** [comment]
Yo dood - I got dis.

**Comment by JoeKarlsson1** [comment]
Submitted PR for this issue.

**Comment by JoeKarlsson** [comment]
Fixed up issues and made the styles consistent with the rest of the site. I have resubmitted my PR for review.

**Comment by JoeKarlsson** [comment]
PR Merged
