### ISSUE TITLE
Fix employer scroller on home page

### ISSUE THREAD

**Issue by jaywon** [devleague/devleague-website#5]

**Comment by JoeKarlsson1** [comment]
Add featured to the CMS on only show featured on the homepage.

**Comment by JoeKarlsson1** [comment]
Got rid of the carousel on the homepage - I still need to add a featured check on airship tho.

**Comment by jaywon** [comment]
Shoooots

**Comment by JoeKarlsson1** [comment]
I fixed this - If featured is added as a caption to the employeer network in Airship it will be shown on the homepage.
