### ISSUE TITLE
Change e-mail us button on privacy page to change to  visible e-mail address on privacy page

### ISSUE THREAD

**Issue by jaywon** [devleague/devleague-website#57]
Like the idea of not having e-mail address displayed on site to prevent spam scrapers but `mailto` is pretty old so maybe when user clicks(proves  they're human) replace button with actual e-mail address.

**Comment by sgnl** [comment]
reference: http://techblog.tilllate.com/2008/07/20/ten-methods-to-obfuscate-e-mail-addresses-compared/

**Comment by sgnl** [comment]
I ended up not using the obfuscation techniques in article above.
