### ISSUE TITLE
Create a Projects page to showcase projects

### ISSUE THREAD

**Issue by jaywon** [devleague/devleague-website#64]
We want to showcase student projects but we need to be mindful of dead links

**Comment by sgnl** [comment]
@jaywon I could write a client-side JS script to test projects listed and remove them if necessary.

**Comment by sgnl** [comment]
This is what I got so far, two states using materialcss' card component

First is listing (not opened):
![image](https://cloud.githubusercontent.com/assets/3915598/20856514/ab116b1e-b8b4-11e6-8fc7-8e1b320909fe.png)

Click for description (opened):
![image](https://cloud.githubusercontent.com/assets/3915598/20856516/be534648-b8b4-11e6-95c9-16cc73f06233.png)

**Comment by sgnl** [comment]
Maybe instead of static images, I could create GIFs. Maybe after we launch.

**Comment by sgnl** [comment]
Merged 5475e64

Closing issue.
