### ISSUE TITLE
Have navigation elements be dynamic and not hard coded for courses offered

### ISSUE THREAD

**Issue by jaywon** [devleague/devleague-website#66]
Links are hard coded and not dynamic in main nav.

**Comment by sgnl** [comment]
waiting word from Airship team on how to tackle this with Propellers before trying JS/XHR solution via API endpoints.

**Comment by sgnl** [comment]
Going with this issue and closing duplicate #28.

**Comment by sgnl** [comment]
Going with the javascript/XHR solution until the "global helpers" feature is implemented into airship.

**Comment by sgnl** [comment]
Closing
