### ISSUE TITLE
Fix  navigation menu dropdown size

### ISSUE THREAD

**Issue by sgnl** [devleague/devleague-website#74]
Currently the navigation looks like this:

![image](https://cloud.githubusercontent.com/assets/3915598/21280954/69379216-c38d-11e6-8203-614f6c6a08f6.png)

Maybe fix could look like this:

![image](https://cloud.githubusercontent.com/assets/3915598/21280966/8b82208e-c38d-11e6-9a5d-0814219faba2.png)

**Comment by jaywon** [comment]
Yes plz! That was driving me crazy. :sob:
