### ISSUE TITLE
Home Page Content Recommendations

### ISSUE THREAD

**Issue by senakamura** [devleague/devleague-website#87]
Going to set a `max-width` on all sections areas to squish up content and have easier readability for users. 

Section: **Apply Today**
- Might need one more sentence of content or kill the text.

Section: **Facts & Figures** 
Kill the section or add double or triple the content currently in there.

Section: **Funding Your Education**
- Convert links to grid? 
- kill Oahu WorkLinks

Section: **Employer Network** 
- Add Headline
- Add sentence or two? 
- Convert logos into 6 column rows instead. 
- **ALL** Logos should either be transparent PNGs or put into cards with same backgrounds for consistency. The mixing leaves little to be desired.

**Comment by jaywon** [comment]
Cleaning up cruft issues.
